# Generated by Django 4.1 on 2022-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='img/agent')),
                ('bio', models.TextField()),
                ('instagram', models.CharField(max_length=80, unique=True)),
                ('telegram', models.CharField(max_length=80, unique=True)),
                ('whatsapp', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
