# Generated by Django 4.1 on 2022-08-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agent.agent'),
            preserve_default=False,
        ),
    ]
