# Generated by Django 4.1 on 2022-08-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_requestvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestvisit',
            old_name='text',
            new_name='Message',
        ),
    ]
