# Generated by Django 4.1 on 2022-08-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_rename_text_requestvisit_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestvisit',
            old_name='Message',
            new_name='message',
        ),
    ]
