# Generated by Django 4.1 on 2022-08-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_phone'),
        ('house', '0005_rename_message_requestvisit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestvisit',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
