# Generated by Django 4.1 on 2022-08-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_phone'),
        ('house', '0006_alter_requestvisit_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestvisit',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestvisit',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
            preserve_default=False,
        ),
    ]
